### ISSUE TITLE
Handle multiple users

### ISSUE THREAD

**Issue by rashad** [jarlefosen/alfred-gcloud-shortcuts#13]
Hey there, 

Here's a quick question that should be a no brainer to you all.

I have multiple Google accounts logged in my browser meaning that every time I access a Google URL I have a **`authuser` parameter.** For instance gmail is `https://mail.google.com/mail/u/0/#inbox`. 

By default the extension sends me a URL with no`authuser` so default 0.

Unfortunately the account I use for GCP is `authuser=5` with url like `https://console.cloud.google.com/bigquery?project=aweseomeproject&authuser=5` and since I have a lot of other alfred shortcuts and URL configured with those numbers I kind don't want to change them all. 

Thus I am wondering is there is, by any chance, a way to **include that parameter** in the extension config?

Thanks all,
Cheers from France 👋 🇫🇷

**Comment by jarlefosen** [comment]
Hello there!
Good question, and I'm sorry for the late reply.

I just got around to looking at the issue and I've come up with a possible solution in #15 
Would you mind checking it out @rashad to see if this does solve your issue?

👋 🇳🇴

**Comment by rashad** [comment]
Hey! 
Thanks a lot for your awesome answer! You're blazing fast ⚡️ 
One question that comes to my mind while reading your PR is, would one need to specify the `authuser` parameter each time the workflow is invoked or would it be set globally? 

You rock 🤘 

🇫🇷❤️

**Comment by jarlefosen** [comment]
You only need to specify this in the workflow configuration once. The argument will automatically be set on all the URLs for you. You and I can have different `authuser` values.

Open Alfred settings, go to this worfklow `Google Cloud Shortcuts`, and click the config button `[x]`
![image](https://user-images.githubusercontent.com/2993240/78842558-96fd6900-7a00-11ea-9aec-d0ad4c29c00c.png)

Here you can specify variables for the workflow.
If `authuser` is set then it will be used in all the URLs for you. E.g.: `?&authuser=5`

![image](https://user-images.githubusercontent.com/2993240/78842458-4e45b000-7a00-11ea-8043-17b25d4c5754.png)

**Comment by jarlefosen** [comment]
I have now released this feature in v2.0.6 
https://github.com/jarlefosen/alfred-gcloud-shortcuts/releases/tag/v2.0.6

Please check it out, hopefully it's helpful for you to be able to specify the default `authuser`

**Comment by rashad** [comment]
Just tested and it works like a charm !! 🍀  Thank you so so much for your help

![Alt Text](https://media.giphy.com/media/GVMhZwYv8U5NK/200w_d.gif)

**Comment by jarlefosen** [comment]
Happy to help out, and I'm glad it worked for you!
