### ISSUE TITLE
Workflow Incompatible o Alfred 3.8.6

### ISSUE THREAD

**Issue by avivshafir** [jarlefosen/alfred-gcloud-shortcuts#19]
Is this workflow only for alfred version 4?

**Comment by jarlefosen** [comment]
Hi @avivshafir, I was hoping it would be compatible with Alfred 3 + 4.
It's using AwGo under the hood (https://github.com/deanishe/awgo/), but I might have done something that isn't compatible with both versions.

Could you help me track down the issue?
Do you see an error message, or is the workflow just not showing up in the workflow overview?
Which version are you trying to use?

The binaries being used are not signed which is an obstacle when installing or updating the workflow as you have to get your system to allow running them. It is cumbersome.

**Comment by avivshafir** [comment]
@jarlefosen I can help, but the workflow just doesn't load,  I get a message that the workflow is incompatible. 
I tried to download multiple versions from the releases tab.

Not sure if it's my alfred version or not

will try to update later if I find something

**Comment by avivshafir** [comment]
I upgraded to alfred 4 in the end

**Comment by jarlefosen** [comment]
That's probably the easiest solution 😅 

Did you get the workflow working after upgrading?
As I haven't gotten the code signed and notarized with Apple it will be prompting that the binaries are unsafe each time you download a new version of this workflow.

**Comment by avivshafir** [comment]
@jarlefosen I got it working eventually.. Yes Apple made it very annoying to install as you describe

**Comment by jarlefosen** [comment]
Great! I'll close this issue then 👍 

I will take a stab at fixing this notarization issue in the future.
