### ISSUE TITLE
Support for more resources

### ISSUE THREAD

**Issue by trietsch** [jarlefosen/alfred-gcloud-shortcuts#23]
Hi, I'm an avid user of your workflow, absolutely love it!

There are some products missing, so I'll create a PR with the products that I'd like to see added :)
- Cloud DNS
- Secret Manager
- Artifact Registry

**Comment by jarlefosen** [comment]
I'm glad you like it, and I'm always happy to add more product links from PRs :)

**Comment by jarlefosen** [comment]
New release available https://github.com/jarlefosen/alfred-gcloud-shortcuts/releases/tag/v2.0.11
