### ISSUE TITLE
Release workflow itself

### ISSUE THREAD

**Issue by nikivdev** [jarlefosen/alfred-gcloud-shortcuts#3]
Please release the workflow itself on GitHub as a release you can download.

[AwGo](https://github.com/deanishe/awgo) Go library lets you easily add auto updating feature to the workflow.

Thank you.

**Comment by trietsch** [comment]
I'm also interested in the workflow itself. @jarlefosen, could you release the workflow?

**Comment by jarlefosen** [comment]
Hi, so sorry that I didn't react to this before now.

Should I just use a tagged release `v1.0.0` of this repo and attach a workflow export?

@nikitavoloboev the `AwGo` lib looks interesting, defining the workflow as a Go app would certainly be more elegant than gluing it together with different shell scripts and filters. I'll try and look into this some time!

**Comment by trietsch** [comment]
No problem! Yes, you can just make a release like that. :)

**Comment by trietsch** [comment]
@jarlefosen Just a reminder, in case you don't receive notifications

**Comment by jarlefosen** [comment]
Hi there, I tried tidying up some stuff in the source and then released the workflow.
You will likely have to refresh the projects `g-refresh` the first time after installing this.

https://github.com/jarlefosen/alfred-gcloud-shortcuts/releases/tag/v1.0.0

**Comment by trietsch** [comment]
Thanks, works great!

**Comment by nikivdev** [comment]
@jarlefosen It doesn't load the workflow to Alfred after I double click the `.alfredworkflow` file from releases. What am I doing wrong?

**Comment by jarlefosen** [comment]
That's odd. I'm not too familiar with Alfred unfortunately.
Which version of Alfred do you have? Do you see any indication of an error message? @nikitavoloboev

**Comment by nikivdev** [comment]
Im on v3.8.1

No error message that I can see

**Comment by deanishe** [comment]
I just downloaded the workflow file and had a look. There's no `info.plist` file in it, so it's not a valid workflow.

@jarlefosen You can export your workflow from Alfred (right-click on it in Alfred Preferences and choose "Export…").

@nikitavoloboev Why didn't you unzip the workflow and look inside? You've built enough workflows to know what to look for.

**Comment by nikivdev** [comment]
> Why didn't you unzip the workflow and look inside?

Stressful day. Didn't think of it. 😞

**Comment by nikivdev** [comment]
> Thanks, works great!

But also how did @trietsch get it working then 🤔

**Comment by trietsch** [comment]
@nikitavoloboev I had the same when importing the workflow. I just made a workflow myself with the `info.plist` in it. Somehow when you export this workflow, Alfred doesn't export it correctly. 
Btw, I sent my findings to this topic by replying to the GitHub mail (which should post it here), but apparently it didn't. But I'm glad you guys found it out.

**Comment by jarlefosen** [comment]
This is weird. I am exporting the workflow via the GUI as @deanishe says, but when I'm unzipping it there's no `info.plist` there. Do you have any idea why that may be?

The only contents are `icon.png` and `bin/butler-darwin`.

**Comment by nikivdev** [comment]
Not sure why that happens. But you can also try [this script](https://gist.github.com/deanishe/b16f018119ef3fe951af) to build the workflow. 

`workflow-build.py <dir-containing-workflowfiles>`

**Comment by jarlefosen** [comment]
@nikitavoloboev I chose to write the zipper in the Makefile to keep the process simple.

I released v1.0.1 which changes the name of the a workflow but more importantly contains the info.plist file! Hopefully this works for you.

https://github.com/jarlefosen/alfred-gcloud-shortcuts/releases/tag/v1.0.1

**Comment by nikivdev** [comment]
Thanks @jarlefosen it downloaded

**Comment by deanishe** [comment]
> This is weird. I am exporting the workflow via the GUI as @deanishe says, but when I'm unzipping it there's no info.plist there. Do you have any idea why that may be?

That is weird. How do you have the workflow set up on your machine? Symlinked to the workflow directory? I just downloaded the repo to Alfred's workflow folder and exported it, and it worked fine.

**Comment by jarlefosen** [comment]
It is a symlink between Alfred workflows and my developer directory structure. Really weird that it is able to do exports of the other files but not `info.plist`.

For now the Makefile contains a functioning workaround for the export so it's not an immediate issue. And if all else fails I'll just move the folder to the Alfred workflows directory itself.
